In [38]:
# Import Section 
import matplotlib.pyplot as plt
from sklearn import tree #for decision tree classifier
from sklearn import datasets #for data
from sklearn import metrics #for confusion matric 
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
import csv
import numpy 
import math

In [44]:

content=[]
file="voice.csv"
with open(file, encoding="utf8") as csvfile:
    read= csv.reader(csvfile) # Return a reader object which will iterate over lines in the given csvfile.
    for row in read:
        content.append(row)
#print(content)
# print(content[1:])
def analyse(j): 
    men=[]
    women=[]
    for i in content[1:]:
        if i[20]=="male":
            men.append(float(i[j]))
        else:
            women.append(float(i[j]))

for i in range(20): 
    analyse(i)

# Using only attributes for which mean diff is either >0.05 or <0.05
data=[]
digit=0
for i in content:
    if i[20]=='male':
        digit=0
    elif i[20]=='female':
        digit=1
    data.append( [i[5], i[17], i[7],i[18],i[12], i[6],i[15], i[9], digit] )
    
    
X=[]
y=[]
for i in data[1:]:
    X.append(i[:8])
    y.append(i[8]) # 0 = male, 1 = female
    
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=0)

# Decision Tree
classifier = tree.DecisionTreeClassifier()
classifier.fit(X_train,y_train)
expected= y_test
predict= classifier.predict(X_test)
score = metrics.accuracy_score(y_test, classifier.predict(X_test))
# Confusion Matrix is a performance measurement for machine learning classification.
# To read more abot confusion matrix kindly check this link! 
# https://towardsdatascience.com/understanding-confusion-matrix-a9ad42dcfd62
# 536 rows True Positive and 14 rows False Positive
# 26 rows False Negative and 470 True Negative
print("Decision Tree: Confusion Matrix:\n{0}".format(metrics.confusion_matrix(expected, predict)))
print("Decision Tree: Accuracy Score is: {}\n".format(score))

# Random Forest
rand_forest = RandomForestClassifier()
rand_forest.fit(X_train,y_train)
rf_expected= y_test
rf_predict= rand_forest.predict(X_test)
rf_score = metrics.accuracy_score(y_test, rand_forest.predict(X_test))

print("Random Forest: Confusion Matrix:\n{0}".format(metrics.confusion_matrix(rf_expected, rf_predict)))
print("Random Forest: Accuracy Score is: {}\n".format(rf_score))

# GaussianNB  
GNB = RandomForestClassifier()
GNB.fit(X_train,y_train)
GNB_expected= y_test
GNB_predict= GNB.predict(X_test)
GNB_score = metrics.accuracy_score(y_test, GNB.predict(X_test))

print("GaussianNB: Confusion Matrix:\n{0}".format(metrics.confusion_matrix(GNB_expected, GNB_predict)))
print("GaussianNB: Accuracy Score is: {}\n".format(GNB_score))


# # Logistic Regression
# logistic = LogisticRegression()
# logistic.fit(X_train, y_train)
# logistic_expected= y_test
# logistic_predict= logistic.predict(X_test)
# logistic_score = metrics.accuracy_score(y_test, logistic.predict(X_test))

# print("logistic Regression: Confusion Matrix:\n{0}".format(metrics.confusion_matrix(logistic_expected, logistic_predict)))
# print("logistic Regression: Accuracy Score is: {}\n".format(logistic_score))


# Support Vector Classifier  
svc = SVC()
svc.fit(X_train,y_train)
svc_expected= y_test
svc_predict= svc.predict(X_test)
svc_score = metrics.accuracy_score(y_test, svc.predict(X_test))

print("Support Vector Classifier : Confusion Matrix:\n{0}".format(metrics.confusion_matrix(svc_expected, svc_predict)))
print("Support Vector Classifier : Accuracy Score is: {}\n".format(svc_score))


# KNeighbors Classifier
KNeighbors = KNeighborsClassifier()
KNeighbors.fit(X_train,y_train)
kn_expected= y_test
kn_predict= rand_forest.predict(X_test)
kn_score = metrics.accuracy_score(y_test, KNeighbors.predict(X_test))

print("KNeighbors: Confusion Matrix:\n{0}".format(metrics.confusion_matrix(kn_expected, kn_predict)))
print("KNeighbors: Accuracy Score is: {}\n".format(kn_score))



Decision Tree: Confusion Matrix:
[[533  17]
 [ 25 471]]
Decision Tree: Accuracy Score is: 0.9598470363288719

Random Forest: Confusion Matrix:
[[544   6]
 [ 15 481]]
Random Forest: Accuracy Score is: 0.9799235181644359

GaussianNB: Confusion Matrix:
[[544   6]
 [ 14 482]]
GaussianNB: Accuracy Score is: 0.9808795411089866



c:\users\hozrifai\desktop\junior\venv\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\hozrifai\desktop\junior\venv\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\hozrifai\desktop\junior\venv\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


Support Vector Classifier : Confusion Matrix:
[[430 120]
 [166 330]]
Support Vector Classifier : Accuracy Score is: 0.7265774378585086

KNeighbors: Confusion Matrix:
[[544   6]
 [ 15 481]]
KNeighbors: Accuracy Score is: 0.7208413001912046



c:\users\hozrifai\desktop\junior\venv\lib\site-packages\sklearn\utils\validation.py:563: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  FutureWarning)
c:\users\hozrifai\desktop\junior\venv\lib\site-packages\sklearn\utils\validation.py:563: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  FutureWarning)
c:\users\hozrifai\desktop\junior\venv\lib\site-packages\sklearn\utils\validation.py:563: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is reco